"""
This type stub file was generated by pyright.
"""

from .core import HTML

class Renderer:
    def __init__(self, tag: HTML, html_indent: int = ...) -> None:
        ...
    
    def render(self) -> str:
        ...
    
    def get_inner_text(self, tag: HTML) -> str:
        ...
    
    def get_inner_html(self, tag: HTML) -> str:
        ...
    
    def get_close_tag(self, tag: HTML) -> str:
        ...
    
    def get_open_tag(self, tag: HTML) -> str:
        ...
    


